INSERT INTO tb_category(name, description) VALUES ('Design Gráfico e Digital', 'Transforme ideias em imagens atraentes e funcionais com serviços de design gráfico e digital.')
INSERT INTO tb_category(name, description) VALUES ('Desenvolvimento Web', 'Construa uma presença online sólida com desenvolvimento web frontend, backend e aplicativos móveis personalizados.')
INSERT INTO tb_category(name, description) VALUES ('Marketing Digital', 'Alcance e envolva seu público-alvo através de estratégias de marketing digital, incluindo SEO, mídias sociais e publicidade online.')
INSERT INTO tb_category(name, description) VALUES ('Consultoria Empresarial', 'Obtenha orientação estratégica e prática para impulsionar o crescimento e eficiência do seu negócio.')
INSERT INTO tb_category(name, description) VALUES ('Saúde e Bem-Estar', 'Cuide do seu corpo e mente com serviços de saúde, fitness, nutrição e bem-estar personalizados.')

INSERT INTO tb_job(name, description) VALUES ('Design de Logotipo', 'Criação de logotipos exclusivos e impactantes para representar a identidade de uma marca.')
INSERT INTO tb_job(name, description) VALUES ('Web Design Responsivo', 'Desenvolvimento de designs atraentes e funcionais para sites que se adaptam a diferentes dispositivos.')
INSERT INTO tb_job(name, description) VALUES ('Ilustração Digital', 'Ilustrações artísticas e digitais para livros, mídia online, ou material promocional.')
INSERT INTO tb_job(name, description) VALUES ('Infográficos Interativos', 'Criação de infográficos dinâmicos para apresentar informações de maneira visualmente atraente.')
INSERT INTO tb_job(name, description) VALUES ('Arte para Redes Sociais', 'Desenvolvimento de imagens e gráficos exclusivos para uso em plataformas de mídias sociais.')
INSERT INTO tb_job(name, description) VALUES ('Desenvolvimento Frontend', 'Implementação de interfaces de usuário interativas e responsivas.')
INSERT INTO tb_job(name, description) VALUES ('Desenvolvimento Backend', 'Construção de lógica de servidor robusta para suportar a funcionalidade do lado do cliente.')
INSERT INTO tb_job(name, description) VALUES ('Desenvolvimento de Aplicativos Móveis', 'Criação de aplicativos para dispositivos móveis, oferecendo uma experiência de usuário fluida.')
INSERT INTO tb_job(name, description) VALUES ('Desenvolvimento de E-commerce', 'Construção de plataformas de comércio eletrônico para venda online.')
INSERT INTO tb_job(name, description) VALUES ('Integração de APIs', 'Conexão de diferentes serviços e sistemas através de integrações de API.')
INSERT INTO tb_job(name, description) VALUES ('Gestão de Mídias Sociais', 'Planejamento e execução de estratégias de mídias sociais para construir presença online.')
INSERT INTO tb_job(name, description) VALUES ('SEO (Otimização de Mecanismos de Busca)', 'Otimização de conteúdo online para melhorar o ranking nos resultados de busca.')
INSERT INTO tb_job(name, description) VALUES ('Publicidade Online', 'Criação e gerenciamento de campanhas de publicidade paga em plataformas online.')
INSERT INTO tb_job(name, description) VALUES ('Email Marketing', 'Desenvolvimento de campanhas de email eficazes para engajar e reter clientes.')
INSERT INTO tb_job(name, description) VALUES ('Marketing de Conteúdo', 'Criação e distribuição de conteúdo relevante para atrair e manter uma audiência.')
INSERT INTO tb_job(name, description) VALUES ('Planejamento Estratégico', 'Desenvolvimento de estratégias de longo prazo para o crescimento e sucesso da empresa.')
INSERT INTO tb_job(name, description) VALUES ('Gestão de Projetos', 'Supervisão e implementação eficiente de projetos para atingir metas específicas.')
INSERT INTO tb_job(name, description) VALUES ('Análise de Dados Empresariais', 'Coleta e interpretação de dados para fornecer insights acionáveis.')
INSERT INTO tb_job(name, description) VALUES ('Assessoria Jurídica Empresarial', 'Consultoria em questões jurídicas relacionadas a negócios e transações comerciais.')
INSERT INTO tb_job(name, description) VALUES ('Treinamento em Desenvolvimento de Equipe', 'Oferta de programas de treinamento para melhorar habilidades e desempenho da equipe.')
INSERT INTO tb_job(name, description) VALUES ('Coaching de Saúde', 'Apoio e orientação personalizada para melhorar a saúde física e mental.')
INSERT INTO tb_job(name, description) VALUES ('Treinamento Pessoal', 'Desenvolvimento de programas de exercícios personalizados e treinamento físico.')
INSERT INTO tb_job(name, description) VALUES ('Nutrição Personalizada', 'Planejamento de dietas personalizadas para atender às necessidades individuais.')
INSERT INTO tb_job(name, description) VALUES ('Terapia Psicológica', 'Fornecimento de serviços de aconselhamento e terapia para saúde mental.')
INSERT INTO tb_job(name, description) VALUES ('Yoga e Meditação', 'Oferta de práticas para melhorar o equilíbrio, flexibilidade e bem-estar geral.')

INSERT INTO job_category(category_id, job_id) VALUES (1, 1)
INSERT INTO job_category(category_id, job_id) VALUES (1, 2)
INSERT INTO job_category(category_id, job_id) VALUES (2, 2)
INSERT INTO job_category(category_id, job_id) VALUES (1, 3)
INSERT INTO job_category(category_id, job_id) VALUES (1, 4)
INSERT INTO job_category(category_id, job_id) VALUES (1, 5)
INSERT INTO job_category(category_id, job_id) VALUES (2, 6)
INSERT INTO job_category(category_id, job_id) VALUES (2, 7)
INSERT INTO job_category(category_id, job_id) VALUES (2, 8)
INSERT INTO job_category(category_id, job_id) VALUES (2, 9)
INSERT INTO job_category(category_id, job_id) VALUES (2, 10)
INSERT INTO job_category(category_id, job_id) VALUES (3, 10)
INSERT INTO job_category(category_id, job_id) VALUES (1, 11)
INSERT INTO job_category(category_id, job_id) VALUES (3, 11)
INSERT INTO job_category(category_id, job_id) VALUES (2, 12)
INSERT INTO job_category(category_id, job_id) VALUES (3, 12)
INSERT INTO job_category(category_id, job_id) VALUES (1, 13)
INSERT INTO job_category(category_id, job_id) VALUES (3, 13)
INSERT INTO job_category(category_id, job_id) VALUES (3, 14)
INSERT INTO job_category(category_id, job_id) VALUES (3, 15)
INSERT INTO job_category(category_id, job_id) VALUES (4, 16)
INSERT INTO job_category(category_id, job_id) VALUES (4, 17)
INSERT INTO job_category(category_id, job_id) VALUES (4, 18)
INSERT INTO job_category(category_id, job_id) VALUES (4, 19)
INSERT INTO job_category(category_id, job_id) VALUES (4, 20)
INSERT INTO job_category(category_id, job_id) VALUES (5, 21)
INSERT INTO job_category(category_id, job_id) VALUES (5, 22)
INSERT INTO job_category(category_id, job_id) VALUES (5, 23)
INSERT INTO job_category(category_id, job_id) VALUES (5, 24)
INSERT INTO job_category(category_id, job_id) VALUES (5, 25)

INSERT INTO tb_user(name, email, password, birth_date, phone, created_at) VALUES ('Alex Silva', 'alex@gmail.com', '$2a$12$iHi3KxsRao/kuaOyfAxlx.oyWArI0lPh25cmB9XAw648Virw85T8m', '1980-01-10', '93991223344', TIMESTAMP WITH TIME ZONE '2020-11-20T03:00:00Z')
INSERT INTO tb_user(name, email, password, birth_date, phone, created_at) VALUES ('Maria Rocha', 'maria@gmail.com', '$2a$12$iHi3KxsRao/kuaOyfAxlx.oyWArI0lPh25cmB9XAw648Virw85T8m', '1995-05-18', '93992345678', TIMESTAMP WITH TIME ZONE '2020-12-30T03:00:00Z')

INSERT INTO tb_advertising(title, description, price, created_at, updated_at, img_url, job_id, seller_id) VALUES ('Faço sua logo', 'Faço sua logo aqui nesse serviço', 100.00, TIMESTAMP WITH TIME ZONE '2021-11-20T03:00:00Z', TIMESTAMP WITH TIME ZONE '2022-11-20T03:00:00Z', 'google.com/img', 1, 1)

INSERT INTO tb_contracter_ad(contracter_id, advertising_id, date, status) VALUES (2, 1, TIMESTAMP WITH TIME ZONE '2020-12-30T03:00:00Z', 2)

INSERT INTO tb_review(text, created_at, updated_at, star_rate, id_advertising) VALUES ('Muito bom até o momento', TIMESTAMP WITH TIME ZONE '2020-12-30T03:00:00Z', null, 4, 1)